// TODO: 실제 KIA 챔피언스 필드 공식 예매 기준 가격표로 교체 필요 (현재는 UI 확인용 목업 값)

export type FanTag = 'home' | 'away' | 'neutral'

export type SeatZone = {
  id: string
  zoneName: string // 구역 구분 (예: "테이블석")
  blockName: string // 블록 (예: "1루 A블록")
  weekdayPrice: number // 평일 1석 가격
  weekendPrice: number // 주말 1석 가격
  cheerScore: number // 0~5
  viewScore: number // 0~5
  comfortScore: number // 0~5
  fanTag: FanTag
  maxParty: number // 해당 구역 권장 최대 인원
}

export const SEAT_ZONES: SeatZone[] = [
  {
    id: 'outfield-free',
    zoneName: '외야 자유석',
    blockName: '외야 잔디 자유석',
    weekdayPrice: 8000,
    weekendPrice: 10000,
    cheerScore: 2,
    viewScore: 2,
    comfortScore: 1,
    fanTag: 'neutral',
    maxParty: 10,
  },
  {
    id: 'outfield-fixed',
    zoneName: '외야지정석',
    blockName: '중앙 외야 지정석',
    weekdayPrice: 10000,
    weekendPrice: 12000,
    cheerScore: 3,
    viewScore: 2,
    comfortScore: 2,
    fanTag: 'neutral',
    maxParty: 8,
  },
  {
    id: 'sky-zone',
    zoneName: '스카이존',
    blockName: '4층 스카이 지정석',
    weekdayPrice: 11000,
    weekendPrice: 13000,
    cheerScore: 1,
    viewScore: 3,
    comfortScore: 3,
    fanTag: 'neutral',
    maxParty: 6,
  },
  {
    id: 'infield-3b',
    zoneName: '내야지정석',
    blockName: '3루 내야지정석',
    weekdayPrice: 13000,
    weekendPrice: 16000,
    cheerScore: 3,
    viewScore: 4,
    comfortScore: 3,
    fanTag: 'neutral',
    maxParty: 6,
  },
  {
    id: 'infield-1b',
    zoneName: '내야지정석',
    blockName: '1루 내야지정석',
    weekdayPrice: 13000,
    weekendPrice: 16000,
    cheerScore: 4,
    viewScore: 4,
    comfortScore: 3,
    fanTag: 'home',
    maxParty: 6,
  },
  {
    id: 'exciting',
    zoneName: '익사이팅석',
    blockName: '1루 필드 익사이팅석',
    weekdayPrice: 15000,
    weekendPrice: 18000,
    cheerScore: 3,
    viewScore: 5,
    comfortScore: 2,
    fanTag: 'neutral',
    maxParty: 4,
  },
  {
    id: 'cheer-1b',
    zoneName: '응원 지정석',
    blockName: '1루 응원단상 A블록',
    weekdayPrice: 16000,
    weekendPrice: 19000,
    cheerScore: 5,
    viewScore: 3,
    comfortScore: 2,
    fanTag: 'home',
    maxParty: 6,
  },
  {
    id: 'away-cheer',
    zoneName: '원정 응원석',
    blockName: '3루 원정 응원 지정석',
    weekdayPrice: 16000,
    weekendPrice: 19000,
    cheerScore: 5,
    viewScore: 3,
    comfortScore: 2,
    fanTag: 'away',
    maxParty: 6,
  },
  {
    id: 'family',
    zoneName: '패밀리석',
    blockName: '3루 패밀리 테이블',
    weekdayPrice: 20000,
    weekendPrice: 24000,
    cheerScore: 2,
    viewScore: 3,
    comfortScore: 4,
    fanTag: 'neutral',
    maxParty: 6,
  },
  {
    id: 'k9',
    zoneName: 'K9석',
    blockName: '홈플레이트 뒤 K9석',
    weekdayPrice: 25000,
    weekendPrice: 30000,
    cheerScore: 4,
    viewScore: 3,
    comfortScore: 4,
    fanTag: 'neutral',
    maxParty: 4,
  },
  {
    id: 'table',
    zoneName: '테이블석',
    blockName: '1루 프리미엄 테이블석',
    weekdayPrice: 30000,
    weekendPrice: 35000,
    cheerScore: 2,
    viewScore: 3,
    comfortScore: 5,
    fanTag: 'neutral',
    maxParty: 4,
  },
  {
    id: 'champion',
    zoneName: '챔피언석',
    blockName: '중앙 챔피언석',
    weekdayPrice: 45000,
    weekendPrice: 50000,
    cheerScore: 2,
    viewScore: 4,
    comfortScore: 5,
    fanTag: 'neutral',
    maxParty: 4,
  },
  {
    id: 'premium',
    zoneName: '프리미엄석',
    blockName: '백네트 프리미엄석',
    weekdayPrice: 60000,
    weekendPrice: 70000,
    cheerScore: 2,
    viewScore: 5,
    comfortScore: 4,
    fanTag: 'neutral',
    maxParty: 4,
  },
  {
    id: 'skybox',
    zoneName: '스카이박스',
    blockName: '프라이빗 스카이박스',
    weekdayPrice: 120000,
    weekendPrice: 140000,
    cheerScore: 1,
    viewScore: 4,
    comfortScore: 5,
    fanTag: 'neutral',
    maxParty: 20,
  },
]
